### ISSUE TITLE
githubの活動数をチェックするタスクがこける

### ISSUE THREAD

**Issue by kokoichi206** [kokoichi206/routines#1]
スケジュール実行してるタスクが失敗している。
引数の渡し方がまずいらしい

### [03/07](https://github.com/kokoichi206/routines/runs/5449908625?check_suite_focus=true)
```
python action_checker/events.py \
    *** \
    *** \
    ***
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/kokoichi206/routines/runs/5449908625?check_suite_focus=true#step:5:3).8.12/x6[4](https://github.com/kokoichi206/routines/runs/5449908625?check_suite_focus=true#step:5:4)
Traceback (most recent call last):
  File "action_checker/events.py", line 9[7](https://github.com/kokoichi206/routines/runs/5449908625?check_suite_focus=true#step:5:7), in <module>
    steps = list(map(int, sys.argv[3].split(" ")))
ValueError: invalid literal for int() with base 10: 'kqns[9](https://github.com/kokoichi206/routines/runs/5449908625?check_suite_focus=true#step:5:9)1'
Error: Process completed with exit code 1.
```

### [03/08](https://github.com/kokoichi206/routines/runs/5465648479?check_suite_focus=true)
```
python action_checker/events.py \
    *** \
    \"***\" \
    \"***\"
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/kokoichi206/routines/runs/5465648479?check_suite_focus=true#step:5:3).8.12/x6[4](https://github.com/kokoichi206/routines/runs/5465648479?check_suite_focus=true#step:5:4)
Traceback (most recent call last):
  File "action_checker/events.py", line 9[7](https://github.com/kokoichi206/routines/runs/5465648479?check_suite_focus=true#step:5:7), in <module>
    steps = list(map(int, sys.argv[3].split(" ")))
ValueError: invalid literal for int() with base 10: 'kqns[9](https://github.com/kokoichi206/routines/runs/5465648479?check_suite_focus=true#step:5:9)1'
```

**Comment by kokoichi206** [comment]
### events.py の引数
３つの引数を渡す様にしている

1. Line Notify のアクセストークン
2. チェックしたいメンバーのリストをスペース区切り
3. 写真の内容を切り替えるイベント数をスペース区切り

2,3 において、配列を渡す際にスペース区切りで記述しているが、それが異なる引数として認識されてしまうらしい（03/07 のジョブの失敗）

そこで、03/08 においては、

``` sh
python action_checker/events.py \
    ${notify_token} \
    \"${members_array_with_space}\" \
    \"${steps_array_with_space}\"
```

と実行させてあげることで、引数を期待値通りにまとめて渡すことができた（かの様に思われた）

**Comment by kokoichi206** [comment]
### sys.argv の理解
以下のようなファイルを用意 (argv.py)

``` python
import sys

for i in range(len(sys.argv)):
    print(sys.argv[i].split(" "))
```

``` sh
python arg.py \
        "access_token" \
        "a b c" \
        "0 1 5"
['arg.py']
['access_token']
['a', 'b', 'c']
['0', '1', '5']
```

``` sh
members="a b c"; steps="0 1 5"; \
> python arg.py \
        "access_token" \
        \"${members}\" \
>       \"${steps}\"
['arg.py']
['access_token']
['"a', 'b', 'c"']
['"0', '1', '5"']
```

**Comment by kokoichi206** [comment]
### 解決策（案１）
うまく渡すのは諦めて、ユーザー名に使われなさそうな文字を使って連結させる（`\`とか）

`\`で分割する例

```
import sys

for i in range(len(sys.argv)):
    print(sys.argv[i].split("\\"))
```

`\`で引き渡す例

```
members="a\b\c"; steps="0\1\5"; \
python arg.py \
        "access_token" \
        ${members} \
        ${steps}
['arg.py']
['access_token']
['a', 'b', 'c']
['0', '1', '5']
```

#### デメリット？
- `\`がユーザー名として許容される様になるかもしれず、その時は変更が必要
- `\`で分割しているということを、`events.py`側と`Github/secrets`側の両方で認識を合わせることが必要

**Comment by kokoichi206** [comment]
2023/1/6, 草の表示する svg が変わっていた。

Before(おそらく):

``` html
<rect class="ContributionCalendar-day" data-date="2023-01-08" data-level="1" data-count="2" height="10" rx="2" ry="2" width="10" x="-38" y="0">1 contribution on January 8, 2023</rect>
```

After:

``` html
<rect class="ContributionCalendar-day" data-date="2023-01-08" data-level="1" height="10" rx="2" ry="2" width="10" x="-38" y="0">1 contribution on January 8, 2023</rect>
```

svg の属性から data-count が消えていた。
